stages:
  - build-image
  - build-chart
  - deploy

image-job:
  stage: build-image
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - docker build --network host -t $CI_PROJECT_NAME:$CI_PIPELINE_ID .
    - docker login -u admin -p gMaxyOl3fU harbor.onwalk.net/pts
    - docker tag $CI_PROJECT_NAME:$CI_PIPELINE_ID harbor.onwalk.net/pts/$CI_PROJECT_NAME:$CI_PIPELINE_ID
    - docker push harbor.onwalk.net/pts/$CI_PROJECT_NAME:$CI_PIPELINE_ID
    - docker tag $CI_PROJECT_NAME:$CI_PIPELINE_ID harbor.onwalk.net/pts/$CI_PROJECT_NAME:latest
    - docker push harbor.onwalk.net/pts/$CI_PROJECT_NAME:latest

chart-job:
  stage: build-chart
  variables:
    HELM_EXPERIMENTAL_OCI: 1
  script:
    - helm registry login -u admin -p gMaxyOl3fU harbor.onwalk.net/charts
    - helm chart save chart/ harbor.onwalk.net/charts/$CI_PROJECT_NAME
    - helm chart push harbor.onwalk.net/charts/$CI_PROJECT_NAME:0.1.1

deploy-job:
  stage: deploy
  variables:
    HELM_EXPERIMENTAL_OCI: 1
  script:
    - mkdir -pv /chart/
    - helm chart pull harbor.onwalk.net/charts/rust-axum-demo:0.1.1 
    - helm chart export harbor.onwalk.net/charts/rust-axum-demo:0.1.1 -d /chart/
    - helm --kubeconfig /root/.kube/config upgrade --install rust-axum-demo /chart/rust-axum-demo/
