image:
  name: artifact.onwalk.net/k8s/ci-runner:v3.6.1 
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
  - build-image
  - build-chart
  - deploy

image-job:
  stage: build-image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"artifact.onwalk.net/k8s\":{\"auth\":\"$(printf "%s:%s" "admin" "L@bs&d1250" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "artifact.onwalk.net/k8s/rust-demo:latest"
  rules:
    - if: $CI_COMMIT_TAG

chart-job:
  stage: build-chart
  variables:
    HELM_EXPERIMENTAL_OCI: 1
  script:
    - helm repo add sync -u admin -p 'L@bs&d1250' https://artifact.onwalk.net/chartrepo/k8s 
    - helm package chart/
    - helm cm-push rust-axum-demo-0.1.1.tgz sync

deploy-job:
  stage: deploy
  variables:
    HELM_EXPERIMENTAL_OCI: 1
  script:
    - helm repo add stable https://artifact.onwalk.net/chartrepo/k8s
    - helm repo up
    - helm --kubeconfig /root/.kube/config upgrade --install rust-axum-demo  stable/rust-axum-demo
